// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Server_App_Final_Project.Models;

#nullable disable

namespace Web_Server_App_Final_Project.Migrations
{
    [DbContext(typeof(HobbyContext))]
    [Migration("20221103162412_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web_Server_App_Final_Project.Models.Cars", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarID"), 1L, 1);

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarID = 1,
                            Make = "Ford",
                            Model = "Mustang Coupe",
                            Year = 1969
                        },
                        new
                        {
                            CarID = 2,
                            Make = "Ford",
                            Model = "Focus SE",
                            Year = 2010
                        },
                        new
                        {
                            CarID = 3,
                            Make = "Jeep",
                            Model = "J20",
                            Year = 1973
                        });
                });

            modelBuilder.Entity("Web_Server_App_Final_Project.Models.Games", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"), 1L, 1);

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            Genre = "Fighting",
                            Name = "Tekken 7",
                            Platform = "PC, PS4, Xbox",
                            Year = 2017
                        },
                        new
                        {
                            GameID = 2,
                            Genre = "Action-Adventure",
                            Name = "Detroit Become Human",
                            Platform = "PC, PS4, Xbox",
                            Year = 2018
                        },
                        new
                        {
                            GameID = 3,
                            Genre = "Adventure, Indie",
                            Name = "Hollow Knight",
                            Platform = "PC, PS4, Xbox",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("Web_Server_App_Final_Project.Models.Trumpet", b =>
                {
                    b.Property<int>("HornID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HornID"), 1L, 1);

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HornID");

                    b.ToTable("Trumpet");

                    b.HasData(
                        new
                        {
                            HornID = 1,
                            Make = "Advantage",
                            Model = "Yamaha",
                            Year = 2012
                        },
                        new
                        {
                            HornID = 2,
                            Make = "Xeno",
                            Model = "Yamaha",
                            Year = 2022
                        },
                        new
                        {
                            HornID = 3,
                            Make = "Stradivarius",
                            Model = "Bach",
                            Year = 2002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
